#!/bin/bash

run_list() {

cat <<EOT

OS X dotfiles - Nicolas Gallagher - http://nicolasgallagher.com/

Additional software to install

Browsers:
    Firefox
    Google Chrome
    Opera

Development:
    Filezilla
    iTerm 2
    ImageAlpha
    ImageOptim
    VirtualBox
    XAMPP

Other:
    Alfred
    Divvy
    Dropbox
    Flux
    KeePassX
    LimeChat
    Network Connect
    Skype
    uTorrent
    VLC
EOT

# Install fonts
rm ~/Library/Fonts/Inconsolata-dz.otf
wget http://media.nodnod.net/Inconsolata-dz.otf.zip
unzip -q Inconsolata-dz.otf.zip
mv Inconsolata-dz.otf ~/Library/Fonts/
rm Inconsolata-dz.otf.zip

# Install Alfred
echo "Install Alfred from App Store"

# Install iTerm2
wget -O iterm2.zip http://iterm2.googlecode.com/files/iTerm2_v1_0_0.zip
unzip -q iterm2.zip
mv iTerm.app /Applications/
rm iterm2.zip

wget https://raw.github.com/altercation/solarized/master/iterm2-colors-solarized/Solarized%20Dark.itermcolors
wget https://raw.github.com/altercation/solarized/master/iterm2-colors-solarized/Solarized%20Light.itermcolors
mv Solarized*.itermcolors ~/Library/Application\ Support/iTerm/

# Install Sublime Text 2
wget -O SublimeText.dmg http://c758482.r82.cf2.rackcdn.com/Sublime%20Text%202.0.1.dmg
hdiutil mount SublimeText.dmg
cp -R /Volumes/Sublime\ Text\ 2/Sublime\ Text\ 2.app /Applications/
hdiutil unmount /Volumes/Sublime\ Text\ 2
rm SublimeText.dmg

}
