#!/bin/bash

run_list() {

cat <<EOT

OS X dotfiles - Nicolas Gallagher - http://nicolasgallagher.com/

Additional software to install

Browsers:
    Firefox
    Google Chrome
    Opera

Development:
    Filezilla
    iTerm 2
    ImageAlpha
    ImageOptim
    VirtualBox
    XAMPP

Other:
    Alfred
    Divvy
    Dropbox
    Flux
    KeePassX
    LimeChat
    Network Connect
    Skype
    uTorrent
    VLC
EOT

#Checking for Finder
APPLESCRIPT=`cat <<EOF
on run argv
  try
    tell application "Finder"
      set appname to name of application file id "$1"
      return 1
    end tell
  on error err_msg number err_num
    return 0
  end try
end run
EOF`

retcode=`osascript -e "$APPLESCRIPT"`


# Install fonts
echo "Installing Fonts......"
echo "======================"
rm ~/Library/Fonts/Inconsolata-dz.otf
wget http://media.nodnod.net/Inconsolata-dz.otf.zip
unzip -q Inconsolata-dz.otf.zip
mv Inconsolata-dz.otf ~/Library/Fonts/
rm Inconsolata-dz.otf.zip
echo "Fonts installed to ~/Library/Fonts/"
echo "Installing Fonts completed"
echo "=========================="

# Install Alfred
echo "Alfred installation....."
echo "=============================="
echo "Install Alfred from App Store"
echo "=============================="

# Install iTerm2
echo "Installing iterm2......"
echo "======================="
wget -O iterm2.zip http://iterm2.googlecode.com/files/iTerm2_v1_0_0.zip
unzip -q iterm2.zip
mv iTerm.app /Applications/
rm iterm2.zip
echo "Installing iterm2 completed"
echo "==========================="

echo "Fetching solarized colour pallet......"
echo "======================================"
wget https://raw.github.com/altercation/solarized/master/iterm2-colors-solarized/Solarized%20Dark.itermcolors
wget https://raw.github.com/altercation/solarized/master/iterm2-colors-solarized/Solarized%20Light.itermcolors
mv Solarized*.itermcolors ~/Library/Application\ Support/iTerm/
echo "Copied solarized colour pallet to ~/Library/Application\ Support/iTerm/"
echo "Please change the colour pallet in iterm2 to solarized"
echo "==========================="

# Install Sublime Text 2
echo "Installing SublimeText2......"
echo "============================="
wget -O SublimeText.dmg http://c758482.r82.cf2.rackcdn.com/Sublime%20Text%202.0.1.dmg
hdiutil mount SublimeText.dmg
cp -R /Volumes/Sublime\ Text\ 2/Sublime\ Text\ 2.app /Applications/
hdiutil unmount /Volumes/Sublime\ Text\ 2
rm SublimeText.dmg

ln -s "/Applications/Sublime Text 2.app/Contents/SharedSupport/bin/subl" ~/bin/subl
echo "Installing SublimeText2 completed"
echo "================================="

}
