#!/bin/bash

run_node() {

    # Check for npm
    if type_exists 'npm'; then
        e_header "Installing Node.js packages..."

        # List of npm packages
        local packages="yo bower grunt-cli jshint"

        # Install packages globally and quietly
        npm install $packages --global --quiet

        [[ $? ]] && e_success "Done"
    else
        printf "\n"
        e_header "Installing nvm ..."

        # Getting nvm from github repository
        curl https://raw.github.com/creationix/nvm/master/install.sh | sh

        . ~/.nvm/nvm.sh

        e_header "Installing Node js using nvm ..."

        # Installing node using nvm
        nvm install 0.10
        nvm alias default 0.10

    fi

}
